apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: second-container
          image: quay.io/shinoe/test-java-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080