apiVersion: v1
kind: Service
metadata:
  name: second-app-service
spec:
  selector:
    app: second
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 34567
  type: NodePort